version: '2'

services:
  cerebro:
    build: .
    container_name: cerebro
    restart: always
    ports: 
      - "9000:9000"
    links:
      - elasticsearch
    extra_hosts:
      - "esnode1:10.202.101.176"
      - "esnode2:10.202.101.185"
      - "esnode3:10.202.101.186"
  elasticsearch:
    image: elasticsearch:5.1.1
    container_name: elasticsearch
    restart: always
    ports:
      - "9200:9200"
      - "9300:9300"
  kibana:
    image: kibana:5.1.1
    container_name: kibana
    restart: always
    ports:
      - "5601:5601"
    links:
      - elasticsearch